#!/usr/bin/perl
 
# refer libraries
use CGI qw/:standard/;
use DBI;
use File::Copy;

my $file_name = 'report.txt';
open(my $fh, '>', $file_name) or die "Could not open file '$file_name' $!";
print $fh "My second, 5, report generated by perl\n";

# Create CGI and print header
$query = new CGI; 

$dbh = DBI->connect("DBI:mysql:database=1764220_pir;host=pdb19.awardspace.net","1764220_pir", "");

print $fh "1\n";

if (length ($ENV{'QUERY_STRING'}) > 0){
      $buffer = $ENV{'QUERY_STRING'};
      @pairs = split(/&/, $buffer);
      foreach $pair (@pairs){
           ($name, $value) = split(/=/, $pair);
           $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
           $in{$name} = $value; 
      }
}
print $fh "2\n";
if ($in{'greeting'} ne "pirFileUpload"){
   die;
}
print $fh "3\n";
if ($filename = $query->param_fetch('Filedata')->[0]) { 
   wrint $fh "5\n";
	$upload_filehandle = $filename;
	$user_id = $in{'userId'};
   if (not $filename =~ m/\.(gif|jpg|jpeg)$/i) {  
      die "Unacceptable format. Please only use authorized format."; }
   $sth = $dbh->prepare("INSERT INTO rs_photo (file_name,display_name,date_taken,owner_id,enterer_id) values (?,?,DATE(CURRENT_TIMESTAMP),?,?)");
   $sth->execute($filename,$filename,$user_id,$user_id);
   $filename =~ tr/A-Z/a-z/;
   $filename =~ s/\s//g;
   $photo_id = $sth->{mysql_insertid};
   print "$photo_id";
   $filename = $photo_id . $filename;
   $sth = $dbh->prepare("update rs_photo set file_name = ? where id = ?");
   $sth->execute($filename,$photo_id);

   $sth = $dbh->prepare("delete from rs_new_photo where enterer_id = ?");
   $sth->execute("1");
   $sth = $dbh->prepare("insert into rs_new_photo (photo_id,enterer_id) values (?,1)");
   $sth->execute($photo_id);

   open UPLOADFILEORIG, ">rs/photom/orig/$filename"; 
   binmode UPLOADFILE; 
   while ( <$upload_filehandle> ) { 
      print UPLOADFILEORIG; 
   } 
   close UPLOADFILEORIG; 
   system("convert -size 1000x1000 rs/photom/orig/$filename -resize 1200x1200 rs/photom/$filename");
   system("convert -size 400x400 rs/photom/orig/$filename -resize 120x120 rs/photom/thumbnails/$filename");
   if ($@) {
      warn $@; # print the error
   }
}
print $fh "4\n";
$dbh->disconnect();
close $fh;
